version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BackendSamdeploymentStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7hk3gevdmrgx"
s3_prefix = "BackendSamdeploymentStack"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
