version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SampleServerlessBackend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nhpe3yzx369y"
s3_prefix = "SampleServerlessBackend"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

